name: Run Trustify nightly main branch tests

on:
  schedule:
    - cron: "5 3 * * *"
  workflow_dispatch:

jobs:
  main-nightly:
    uses: ./.github/workflows/global-ci.yml
    with:
      operator_bundle: "ghcr.io/trustification/trustify-operator-bundle:latest"
      api_tests_ref: main
      run_api_tests: true
      ui_tests_ref: main
      # TODO
      # We run this against ghcr.io/trustification/trustd:latest which does not contain the
      # latest version of the UI. Therefore the UI tests will always fail.
      # The repository https://github.com/trustification/trustify needs to find a way to continuously
      # update the UI before this property is enabled
      run_ui_tests: false
